# Generated by Django 4.1.7 on 2024-06-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMT', '0002_stock_created_at_stock_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lmt',
            name='current_price',
        ),
        migrations.AddField(
            model_name='stock',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
