# Generated by Django 4.1.7 on 2024-06-04 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMT', '0003_remove_lmt_current_price_stock_current_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lmt',
            name='cost',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='lmt',
            name='quantity',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='current_price',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
