# Generated by Django 4.1.7 on 2024-06-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMT', '0004_alter_lmt_cost_alter_lmt_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='gpt_updated_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
