# Generated by Django 4.1.7 on 2024-06-06 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMT', '0006_alter_stock_gpt_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='gpt_updated_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
