# Generated by Django 4.1.7 on 2023-03-24 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academicworld', '0001_initial'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='facultykeyword',
            index_together={('keyword', 'score')},
        ),
    ]
