# Generated by Django 4.1.7 on 2023-03-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academicworld', '0002_alter_facultykeyword_index_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='group',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
