# Generated by Django 4.1.7 on 2023-03-26 00:00

from django.db import migrations, models
from django.db.models import Sum
from academicworld.constants import CLUSTERMAP


def calculate_group_scores(apps, schema_editor):
    Faculty = apps.get_model('academicworld', 'Faculty')
    for professor in Faculty.objects.all():
        for key, val in CLUSTERMAP.items():
            group_score = professor.facultykeyword_set.filter(keyword__group=val).aggregate(total_score=Sum('score'))['total_score'] or 0
            setattr(professor, key, group_score)
        professor.save()


class Migration(migrations.Migration):

    dependencies = [
        ('academicworld', '0003_keyword_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='group1',
            field=models.FloatField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='group2',
            field=models.FloatField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='group3',
            field=models.FloatField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='group4',
            field=models.FloatField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='group5',
            field=models.FloatField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='group6',
            field=models.FloatField(null=True, blank=True),
        ),
        migrations.RunPython(calculate_group_scores),
    ]
