# Generated by Django 4.1.7 on 2025-05-07 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionitem',
            options={},
        ),
        migrations.AddField(
            model_name='sessionitem',
            name='sold',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sessionitem',
            name='stock',
            field=models.PositiveSmallIntegerField(default=100),
        ),
    ]
