# Generated by Django 4.1.7 on 2025-05-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_sessionitem_options_sessionitem_sold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionitem',
            name='stock',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
