# Generated by Django 4.1.7 on 2025-05-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_menuitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('山茶花鲜奶吐司', '山茶花鲜奶吐司'), ('馅料小吐司', '馅料小吐司'), ('碱水棒', '碱水棒'), ('碱水球', '碱水球')], default='山茶花鲜奶吐司', max_length=20),
        ),
    ]
