# Generated by Django 4.1.7 on 2025-05-08 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='session',
            name='slug',
        ),
    ]
