# Generated by Django 4.1.7 on 2025-05-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_order_customer_name_remove_session_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('吐司(450g)', '吐司(450g)'), ('吐司(250g)', '吐司(250g)'), ('碱水', '碱水'), ('碱水棒', '碱水棒'), ('碱水球', '碱水球')], default='吐司(450g)', max_length=20),
        ),
    ]
