# Generated by Django 4.1.7 on 2025-06-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('大吐司', '大吐司'), ('小吐司', '小吐司'), ('司康', '司康'), ('碱水棒', '碱水棒'), ('碱水球', '碱水球'), ('贝果', '贝果')], default='大吐司', max_length=20),
        ),
    ]
