# Generated by Django 4.1.7 on 2023-12-17 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(null=False, blank=False, help_text='Name of the task.', max_length=255)),
                ('completed', models.BooleanField(default=False, help_text='Status of the task completion.')),
                ('mistress', models.ForeignKey(help_text='The user who assigns the task.', on_delete=django.db.models.deletion.CASCADE, related_name='task_mistress', to=settings.AUTH_USER_MODEL)),
                ('sub', models.ForeignKey(help_text='The user who is responsible for completing the task.', on_delete=django.db.models.deletion.CASCADE, related_name='task_sub', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
