# Generated by Django 4.1.7 on 2024-03-14 00:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmanager',
            name='completed_date',
            field=models.DateTimeField(blank=True, help_text='The date and time the task was completed.', null=True),
        ),
        migrations.AddField(
            model_name='taskmanager',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='The date and time the task was created.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskmanager',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, help_text='The date and time the task was last updated.'),
        ),
    ]
