# Generated by Django 4.1.7 on 2024-06-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('company', models.CharField(max_length=40)),
                ('sector', models.CharField(max_length=40)),
                ('industry', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=20)),
            ],
        ),
    ]
