# Generated by Django 4.1.7 on 2024-11-16 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_strategyrecordanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyOptionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('criteria', models.TextField()),
                ('total_score', models.IntegerField()),
                ('decision', models.CharField(max_length=5)),
                ('weight', models.FloatField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
