# Generated by Django 4.1.7 on 2023-12-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgptinteraction',
            name='content_text',
            field=models.TextField(help_text="The user's input."),
        ),
        migrations.AlterField(
            model_name='chatgptinteraction',
            name='requirement_text',
            field=models.TextField(help_text="The user's requirements."),
        ),
    ]
