# Generated by Django 4.1.7 on 2024-11-24 21:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_expo_push_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(default=datetime.date(1995, 2, 14), verbose_name='Date of Birth'),
        ),
    ]
